name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Restore Cache
      uses: actions/cache@preview
      id: cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
    - name: Install tooling deps 
      run: go get golang.org/x/lint/golint@v0.0.0-20201208152925-83fdc39ff7b5
    - name: Test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        CUSTOM_STORAGE_BUCKET: ${{ secrets.CUSTOM_STORAGE_BUCKET }}
      run: |
        # TODO: move this to env block
        export GOPATH="$(go env GOPATH)"
        export PATH="$GOPATH/bin:$PATH"

        make test-full
